apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
# Use hack/update-sso.sh to compute this for dev-sso auth domain 
  sso: "https://keycloak-dev-sso.apps.lc-dso-pac-494f-1.blueprints.rhecoeng.com/auth/" 
  ingressClass: openshift-default
  hostname: hac.apps.lc-dso-pac-494f-1.blueprints.rhecoeng.com
