apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
  sso: "https://keycloak-dev-sso.apps.lc-dso-pac-494f-1.blueprints.rhecoeng.com/auth/"
  ingressClass: openshift-default
  hostname: keycloak-dev-sso.apps.lc-dso-pac-494f-1.blueprints.rhecoeng.com
